name: Download Files

on:
  schedule:
    - cron: '*/2 * * * *' # This will run every 5 minutes
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Set environment variables
      run: |
        echo "CHANNELS_URL=https://babel-in.xyz/babel-b2ef9ad8f0d432962d47009b24dee465/tata/channels" >> $GITHUB_ENV
        echo "HMAC_URL=https://fox.toxic-gang.xyz/tata/hmac" >> $GITHUB_ENV

    - name: Ensure files exist
      run: |
        touch channels hmac

    - name: Download CHANNELS_URL
      run: |
        curl -o channels "${{ env.CHANNELS_URL }}"

    - name: Download HMAC_URL
      run: |
        curl -o hmac "${{ env.HMAC_URL }}"

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

    - name: Check for changes
      id: check_changes
      run: |
        git add channels hmac
        git status
        git diff --cached --exit-code || echo "changes_detected=true" >> $GITHUB_ENV

    - name: Commit changes
      if: env.changes_detected == 'true'
      run: |
        echo "Changes detected, committing..."
        git commit -m "Update files from URLs" || echo "No changes to commit"

    - name: Push changes
      if: env.changes_detected == 'true'
      run: |
        echo "Pushing changes..."
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git push origin HEAD:${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
